json.extract! @card, :id,
                    :name,
                    :card_text,
                    :card_type,
                    :monster_type,
                    :family,
                    :attack,
                    :defense,
                    :level,
                    :property
